[package]
name = "gpeg"
version = "0.1.0"
authors = ["Jack Moffitt <jack@metajack.im>"]

[dependencies]
glium = "0.13"
clap = "2.0"

[dependencies.jpeg-decoder]
git = "https://github.com/kaksmet/jpeg-decoder"
branch = "gpeg"
